version: "3.1"

services:
  app:
    container_name: app
    restart: always
    build: .
    ports: 
      - "3333:3333"
  
  postgres:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: harun
