version: "3.1"

services:
  app:
    container_name: app
    restart: always
    build: .
    ports: 
      - "3333:5000"
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/harun?schema=public
    depends_on:
      - postgres
    entrypoint: ["bash", "-c", "npx prisma migrate deploy && npx prisma db seed && yarn start"]
  
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: harun
